import turtle
#I
r= turtle.Turtle(shape='classic')
r.screen.bgcolor('black')
r.screen.title('I Love you ')
r.color('white')
r.hideturtle()
r.pensize(10)
r.penup()
r.pencolor('pink')
r.setposition(-100,-10)
r.pendown()
r.setheading(90)
r.forward(80)
r.left(90)
r.forward(25)
r.right(180)
r.forward(50)
r.left(180)
r.forward(25)
r.left(90)
r.forward(80)
r.right(90)
r.forward(25)
r.left(180)
#HEART
r.forward(50)
t = turtle.Turtle(shape='circle')
screen = turtle.Screen()
t.color('red')
t.hideturtle()
t.penup()
t.setposition(0,-10)
t.pendown()
t.begin_fill()
t.fillcolor('red')
t.left(140)
t.forward(50)
t.circle(-25, 200)
t.setheading(60)
t.circle(-25, 200)
t.forward(50)
t.end_fill()
t.speed(10)
#U
g=turtle.Turtle(shape='classic')
g.color('pink')
g.hideturtle()
g.pensize(10)
g.penup()
g.setposition(109,-10)
g.pendown()
g.circle(30,-90)
g.back(45)
g.penup()
g.setposition(109,-10)
g.pendown()
g.setheading(0)
g.circle(30,90)
g.forward(45)
turtle.done
